---
- name: All hosts up-to-date
  hosts: os_arch
  become: yes
  
  tasks:
    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

